### ISSUE TITLE
Keyboard Language Issue

### ISSUE THREAD

**Issue by SpicyTauros** [NickImpact/Pixelmon-Model-Converter#1]
Like I said on the discord:
"Hey I found a "bug" while trying to use the PMC and Blender. So since my default language was using Portuguese, which interprets decimals with " , " instead of " . " the exporter wrote the Smd file with commas for floats so blender is unable to import the Smd. I have fixed the issue by changing the keyboard language to english, just thought I'd let you know in case a similar issue happens."
The version was 8.2.3 from Pixelmon Generations.

**Comment by NickImpact** [comment]
Fixed locally, and issue has also been reported to the Generations team.
